# Generated by Django 3.2.7 on 2021-09-14 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='severity_level',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pins.pin'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='survey_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.survey'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='pins.Tag'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='pins.Topic'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pins.mapuser'),
        ),
    ]
