# Generated by Django 3.2.8 on 2021-11-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongformSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('usage', models.TextField(blank=True)),
                ('frequency', models.TextField(blank=True)),
                ('mode', models.TextField(blank=True)),
                ('mode_issues', models.TextField(blank=True)),
                ('condition_1', models.TextField(blank=True)),
                ('condition_2', models.TextField(blank=True)),
                ('condition_3', models.TextField(blank=True)),
                ('condition_4', models.TextField(blank=True)),
                ('condition_5', models.TextField(blank=True)),
                ('condition_6', models.TextField(blank=True)),
                ('condition_7', models.TextField(blank=True)),
                ('priorities', models.TextField(blank=True)),
                ('ideas', models.TextField(blank=True)),
            ],
        ),
    ]
