# Generated by Django 3.2.8 on 2021-10-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='tags',
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='tag_9',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagGroup',
        ),
    ]
