# Generated by Django 3.2.8 on 2021-11-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_longformsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapuser',
            name='q6',
            field=models.TextField(blank=True),
        ),
    ]
