# Generated by Django 3.2.8 on 2021-11-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_mapuser_q6'),
    ]

    operations = [
        migrations.AddField(
            model_name='longformsurvey',
            name='condition_8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='longformsurvey',
            name='condition_9',
            field=models.TextField(blank=True),
        ),
    ]
